global:
  scrape_interval:  10s                    # How frequently to scrape targets
  evaluation_interval: 10s                 # Evaluate rules every 10 seconds. The default is every 1 minute.


# Rules and alerts are read from the specified file(s)
rule_files:
  - /etc/prometheus/alert.rules.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']


scrape_configs:
  - job_name: 'mongodb'
    static_configs:
      - targets: ['mongodb-exporter:9216']

  - job_name: 'prometheus'
    scrape_interval:  5s
    static_configs:
      - targets: ['localhost:9090']
